### ISSUE TITLE
TLK patching possibilitities

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#567]
So, TSLPatcher can only append new lines to TLK files. Consequentially, there is poor compatibility between mods that edit TLK files in other ways. The Community Patch doesn't fix known errors in dialog.tlk for this reason. But it could...

I've written a program that can perform four different operations on TLK files:
- Append new lines
- Update existing lines
- Insert lines anywhere in the file
- Remove lines

I don't yet have a way of feeding end user instructions into it the way TSLPatcher can read changes.ini, however. I have two concerns to deal with before getting to that.

First, is this worth pursuing for the Community Patch? For the time being, it is not possible to integrate it with TSLPatcher, so it might have to be a separate install. It would be great if it could all be integrated into one installer, but that would happen in the distant future, if ever. In the meantime, users would have to install two things.

Second, I'd need to settle on a file format. I don't think INI is particularly readable for editing lots of text. I think [YAML](https://yaml.org/spec/1.2.2/) is somewhat more readable because it allows for multi-line text. Here is an example of what I'm thinking:

```yaml
example.tlk:
  - do: append
    text: Hello, world! This will be placed at the end of the file.
  - do: append
    text: |
      How block mode works:
      1. Write a TLK parser.
      2. Allow multi-line text.
      3. ???
      4. Profit!
  - do: append
    text: >
      Folded mode allows text that is too long to fit on one line in your text
      editor to be folded into one line after the text is parsed. Each line
      break will be converted into a single space.
  - do: append
    text: But there's more than just text...
    sound_resref: foo_bar      # This is the name of the associated sound file.
    sound_length: 3.14159      # And this is the length in seconds.

# By the way, this is how we do comments. Any characters following a # symbol
# will be ignored. If you need multi-line comments, you need to use multiple #
# symbols like so.

another_example.tlk:           # We can provide instructions for multiple files.
  - do: append
    text_present: true         # Here, we're not specifying what the text is, so
                               # it will default to an empty string.
    sound_resref: baz_xyzzy    # Because we've specified a sound_resref, the
                               # field sound_present is implicitly true.
                               # Otherwise, it would default to false.
    sound_length_present: true # sound_length will default to 0.0 here.
  - do: update
    id: 42                     # The line number in the TLK file, aka StrRef.
    sound_present: false       # No matter what it was before, it's now false.
                               # sound_resref will now be the default.
                               # text and text_present won't change.
                               # Ditto sound_length and sound_length_present.
  - do: remove
    id: 1729                   # It's gone!
  - do: update
    id: 1730
    text: |
      Note that the ID numbers won't be changed until we are finished parsing
      this file, so it's the original line 1730 that will be changed here.
  - do: insert
    id: 1138
    text: |
      Again, ID numbers won't change until everything has been parsed. So if you
      want to insert text at line 2 and line 5 of the original file, say that
      you want to insert at line 2 and line 5 and don't worry about the rest.
```
But I'm worried if it's readable to anyone other than me...

Thoughts?
